# MySQL (Docker)
spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}

# MongoDB (Docker)
spring.mongodb.uri=${SPRING_MONGODB_URI}

# JPA
spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=false

# Logging
logging.level.org.springframework.security=INFO

# JWT
jwt.secret=${JWT_SECRET}
jwt.expiration=${JWT_EXPIRATION}

# Mail (Docker)
spring.mail.username=${SPRING_MAIL_USERNAME}
spring.mail.password=${SPRING_MAIL_PASSWORD}
